[pytest]
python_files = tests.py test_*.py *_tests.py
log_cli = true
log_cli_level = DEBUG
addopts = -s -vv --setup-show
markers =
    radar: tests related to radar KPIs
    camera: tests related to camera KPIs
    fusion: tests related to fusion KPIs
    additional: tests related to all additional KPIs (group marker)
    stability: tests related to confidence stability KPI
    contribution: tests related to sensor contribution balance KPI
    spatial: tests related to spatial alignment error KPI
